# following this page -> https://www.honeybadger.io/blog/django-test-github-actions/

# workflow    - a YAML file that contains a list of instructions for processes.
# job         - step by step instructions for an action
# step        - tasks that can run commands in a job

name: test_docker # name of the actual test, it can be anything
on: [push] # we could also include PR like so: on: [pull_request, push]
jobs:
  build_docker: # no spaces
    runs-on: ubuntu-latest # operating system our code will run on
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      -
        name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          