# following this page -> https://www.honeybadger.io/blog/django-test-github-actions/

# workflow    - a YAML file that contains a list of instructions for processes.
# job         - step by step instructions for an action
# step        - tasks that can run commands in a job

name: test_Django # name of the actual test, it can be anything
on: [push] # we could also include PR like so: on: [pull_request, push]
jobs:
  test_project: # no spaces
    runs-on: ubuntu-latest # operating system our code will run on
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: python manage.py test
  test_project2: # no spaces
    runs-on: ubuntu-latest # operating system our code will run on
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python manage.py test
